language: r
sudo: false
cache: packages
file_glob: true
latex: false
pandoc: false
warnings_are_errors: true

r-packages:
  - roxygen2

r_github_packages:
  - kingaa/pomp
  
addons:
  apt:
    packages:
    - libgit2-dev
  homebrew:
    packages:
    - libgit2

stages:
- name: test
  if: tag IS blank
- name: coverage
  if: tag IS blank
- name: deploy
  if: tag IS present

jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: 3.6.0
    os: linux
  - r: release
    os: osx
  - stage: coverage
    r: release
    os: linux
    r_packages:
    - covr
    script:
    - travis_wait 30 Rscript -e 'covr::codecov()'
  - stage: deploy
    r: release
    os: osx
    script:
    - make binary
    deploy:
      provider: releases
      api-key:
        secure: "B8ZJcx4yG2oBNsmDrDLM7vDAItBqmtMldEh39gSOIhSP4bCZ7tXXjGj9iIsON42Ogzx3f2FU9ZjiBSbrhzHEc+2DuDx7jIUuNFzU1jiCSzZlcKovGuh3mZoSPyxTh0SwEGlKvbJCiXdL0CExhzSsBn9TNacKC9vBw8p8E/b+WhDCak2wdHlBoDPHmNT7ubDN/9GVAtkg+LvIXJS93kRngEScsYHuoRP7QeYGqtuWZ/RiKg3bFNr7uWU5zwHwJWuNnI2wNuBewZjC5o88TGLATk31Rcu28yQOyO2n0XNTjjqjbBp2MV2uwXwpnSBu2kaQyPlm5AFAdFh/B16bMx0odkIOl5Qv3OxYoHDyldwz8PTXvweTQ2xcJXMDDde4uVNczbW2VQevZztK9XT/h+gXiDIAsspXi7R/g8lCRdzxS/ENpbo9hvre48ItVtL7PyYwQ5QBLBxDaDIj7yq4RauEVh73p6xXThKufM4wZHWIiIqEb2B9erEkfWWtU7frxBTGSN+cSGzaH4lUWAxd7ev890awv2KOd57ve8TXFrTHIa8ccV6AFha/A4sedTkO9ZJD8gFG/JycbGtRdQaIULGhx6JgkUkXdQfsRSBn3tL1EhluY/yMQicZ1PG9++z3ORbejiVeLKujMVs/kxoZ3Yi+d6XpRUF/eiafH+WN7kwxoew="
      file_glob: true
      file:
      - circumstance_*.tgz
      - circumstance_*.tar.gz
      skip_cleanup: true
      on:
        tags: true
