language: r
sudo: false
cache: packages
file_glob: true
latex: false
pandoc: false
warnings_are_errors: true
r-packages:
- roxygen2
r_github_packages:
- kingaa/pomp
addons:
  apt:
    packages:
    - libgit2-dev
  homebrew:
    packages:
    - libgit2
stages:
- name: test
  if: tag IS blank
- name: coverage
  if: tag IS blank
- name: deploy
  if: tag IS present
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: 3.6.0
    os: linux
  - r: release
    os: osx
  - stage: coverage
    r: release
    os: linux
    r_packages:
    - covr
    script:
    - travis_wait 30 Rscript -e 'covr::codecov()'
  - stage: deploy
    r: release
    os: osx
    script:
    - make binary
    deploy:
      provider: releases
      api_key:
      secure: GdlgKyvoNJwPnWMUYjGVBuF45BJzelIxAHcvgPSTVmO114wab2ahro/+GAEnRLT/gd6XQhRBrKI64JSqkWxIFRmnlXaaL+DqzDGuZi5goSJ1hd77VhTqBErlLe030P8xUV3SXzh8P8OOuNcxNk5WLdH7E+pLCCeVa/Sg1WSTpgMbBLC4uH7c5eZ1JWYz+LhTYWmGoXnflpy0pzd0tbpAtkBH6OtNkeAsrhGGC9pm6A08KSs9GUB9W2rtee/vkK2hXOehGSpjryoVTaEpXHrzYFRpqGdwI6uyMxwcqA8606xLP886r2AQas/V+zdT8NF+KXhfkoXAUNmSWwn3mcDTMU6glryunjgDKIdNm8TBUcZYlxdJM3Tuc8qYGsTx3FqUyZngdRWaPSoeHQaAfepxl5KwzSwDplfgd9y/9Zl/0qzwldbtpQvOVIbnlJAAQhNFHCpcB2VSnXXP/RaCUdO6hQrqhEM80oKtSKGO6sV8tLavpgADmBGsGfW8hmIM9+TNsy//KM9Ii5VwOWVYg9rGmDFSB6gwcLqujdLsYCvHDcsuND0LjoTNP9yYBavnPVrUv+XBIW57trgvzYD9m3i7zNkSMTdt5SMqfNCa1HCnlrZ/lx5DmMhC9wM35Hdy3U21j8V/90d4FOJu80G+YHfXjn2w6t6sSBziCVn6KvDO9Qo=
      file_glob: true
      file:
      - circumstance_*.tgz
      - circumstance_*.tar.gz
      skip_cleanup: true
      on:
        tags: true
