# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:

name: create release

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  release_name: ${{ vars.repo_name }}_${{ github.ref_name }}

jobs:
  make_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  source_build:
    needs: make_release
    runs-on: ubuntu-latest
    name: Build source tarball
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: r-lib/actions/setup-r@v2.3.1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2.3.1
        with:
          extra-packages: |
            any::pkgbuild

      - name: Build source tarball
        run: |
          R CMD build --force --no-manual --resave-data --compact-vignettes=both --md5 .

      - name: Look around
        run: ls ${{ github.workspace }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.make_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ env.release_name }}.tar.gz
          asset_name: ${{ env.release_name }}.tar.gz
          asset_content_type: application/gzip

  binary_build:
    needs: make_release
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release', ext: 'tgz', content_type: "gzip"}
          - {os: windows-latest, r: 'release', ext: 'zip', content_type: "zip"}

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: r-lib/actions/setup-r@v2.3.1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2.3.1
        with:
          extra-packages: |
            any::pkgbuild

      - name: Build binary
        run: pkgbuild::build(binary=TRUE,manual=TRUE)
        shell: Rscript {0}

      - name: Copying tarball
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          cp ../${{ vars.repo_name }}_* ${{ github.workspace }}/artifacts
          ls ${{ github.workspace }}
          ls ${{ github.workspace }}/artifacts

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.make_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/artifacts/${{ env.release_name }}.${{ matrix.config.ext }}
          asset_name: ${{ env.release_name }}.${{ matrix.config.ext }}
          asset_content_type: application/${{ matrix.config.content_type }}
